import Foundation

// MARK: - SampleSource
//
// Every row in the samples / samples_hourly / samples_daily tables
// is tagged with its origin. "real" means it came from the SMC (or
// a future real read path). "synthetic" means it was generated by
// SyntheticDataGenerator for demo / testing purposes.
//
// The user can clear synthetic rows independently of real ones —
// useful when testing the alert pipeline on real data without
// losing the synthetic data you've already curated.

enum SampleSource: String, Codable, CaseIterable, Identifiable {
    case real      = "real"
    case synthetic = "synthetic"
    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .real:      return "Real"
        case .synthetic: return "Synthetic"
        }
    }
}

// MARK: - Sample
//
// A single point-in-time sensor reading. Persisted to SQLite as a row
// in the `samples` table; also in-memory aggregated into the hourly
// and daily rollup tables.
//
// All numeric fields are optional because a partial read is valid —
// e.g. a laptop with no GPU fan has `fanRPMs == []`, and a sensor can
// transiently fail to read.

struct Sample: Equatable, Identifiable {
    var timestamp: Date
    var cpuTempC:  Double?
    var gpuTempC:  Double?
    var cpuFreqGHz: Double?
    var cpuLoad:   Double?
    var gpuLoad:   Double?
    var cpuPState: [Int]
    var fanRPMs:   [Int]
    var source:    SampleSource = .real

    /// Identifiable identity. Timestamps are unique per minute across the
    /// sampler, and tagging with source lets real and synthetic rows from
    /// the same minute coexist in the database (the dashboard only ever
    /// renders one at a time, but the uniqueness property keeps SwiftUI's
    /// `ForEach` happy).
    var id: String { "\(Int(timestamp.timeIntervalSince1970))-\(source.rawValue)" }

    /// Convenience: aggregate fan RPMs into a single max value for charting.
    /// (We use max rather than mean because thermal alerts should react to
    /// whichever fan is spinning hardest, not the average across fans.)
    var maxFanRPM: Int? {
        guard !fanRPMs.isEmpty else { return nil }
        return fanRPMs.max()
    }

    /// Convenience: take the highest P-State across clusters. P-State is a
    /// qualitative "how fast is the CPU running" index used for bucketing
    /// in the anomaly detector.
    var maxPState: Int? {
        guard !cpuPState.isEmpty else { return nil }
        return cpuPState.max()
    }
}
